services:
  st-source-kaggle:
    profiles:
      - bootcamp
    environment:
      - SUPABASE_URL=${STORYTRENDS_API_URL}
      - SUPABASE_KEY=${STORYTRENDS_API_ANON_KEY}
      - KAGGLE_USERNAME=${KAGGLE_USERNAME:-""}
      - KAGGLE_KEY=${KAGGLE_KEY:-""}
    build:
      context: ./
      dockerfile: ./source-kaggle/Dockerfile
      target: runtime
    volumes:
      - cli-settings:/app/.settings
    extra_hosts:
      - "host.docker.internal:host-gateway"

  source-nodejs:
    profiles:
      - bootcamp
    environment:
      - SUPABASE_URL=${STORYTRENDS_API_URL}
      - SUPABASE_KEY=${STORYTRENDS_API_ANON_KEY}
    build:
      context: ./
      dockerfile: ./source-nodejs/Dockerfile
      target: runtime
    volumes:
      - cli-settings:/usr/src/app/.settings
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  cli-settings:
    name: "storytrends-cli-settings"
    external: true
