services:
  st-source-kaggle:
    profiles:
      - bootcamp
    environment:
      - SUPABASE_URL=${SUPABASE_URL_DOCKER}
      - SUPABASE_KEY=${SUPABASE_ANON_KEY}
    build:
      context: ./
      dockerfile: ./source-kaggle/Dockerfile
      target: runtime
    volumes:
      - cli-settings:/app/.settings
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  model-cache:
  cli-settings:
