services:
  st-dashboard:
    profiles:
      - cli
    environment:
      - SUPABASE_URL=${STORYTRENDS_API_URL}
      - SUPABASE_KEY=${STORYTRENDS_API_ANON_KEY}
    image: public.ecr.aws/i2j9j1s3/storytrends:st-dashboard-rc-latest
    ports:
      - 8050:8050
    volumes:
      - cli-settings:/app/.settings

  st-cli:
    profiles:
      - cli
    environment:
      - SUPABASE_URL=${STORYTRENDS_API_URL}
      - SUPABASE_KEY=${STORYTRENDS_API_ANON_KEY}
    image: public.ecr.aws/i2j9j1s3/storytrends:st-cli-rc-latest
    volumes:
      - cli-settings:/usr/src/app/.settings

  st-demo:
    environment:
      - SUPABASE_URL=${STORYTRENDS_API_URL}
      - SUPABASE_KEY=${STORYTRENDS_API_ANON_KEY}
    ports:
      - 3000:3000
    image: public.ecr.aws/i2j9j1s3/storytrends:st-demo-rc-latest
    volumes:
      - cli-settings:/usr/src/app/.settings

volumes:
  model-cache:
  cli-settings:
