services:
  st-module:
    profiles:
      - bootcamp
    environment:
      - SUPABASE_URL=${STORYTRENDS_API_URL}
      - SUPABASE_KEY=${STORYTRENDS_API_ANON_KEY}
      - KAGGLE_USERNAME=${KAGGLE_USERNAME:-""}
      - KAGGLE_KEY=${KAGGLE_KEY:-""}
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: runtime
    volumes:
      - cli-settings:/app/.settings
    extra_hosts:
      - "host.docker.internal:host-gateway"
volumes:
  cli-settings:
    name: ${CLI_SETTINGS_VOLUME_NAME:-storytrends-cli-settings}
    external: true
